version: '2'
services:
    mysql:
        image: mysql:5.7
        env_file:
            - ./mysql.env
        volumes:
            - ./db/mysql:/var/lib/mysql
    web:
        build: ./
        container_name: web
        ports:
            - 8888:80
        volumes:
            - ./src:/var/www
            - ./init.sh:/var/www/init.sh